#!/bin/bash
##
#Configuration
autologin=yes
usescreen=yes
screenname=vappio
loginuser=root

if [ "autologin" = "yes" ]
then 
    # If used in conjunction with vp-loginprofile
    # SCREENME says to the login that we want to run screen in the startup
    exec /bin/login -f $loginuser SCREENME=$usescreen SCREENNAME=$screenname
else
    exec /bin/login
fi
