#!/usr/bin/env python
#
# This metric takes the output from get-pipeline-conf and adds
# it as metadata to a tag
#
# Required keys:
# All keys output from the get-pipeline-conf metric
import sys

from vappio.webservice import tag

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

# Write our header out
sys.stdout.write('kv\n')

# Iterate over key-value pairs passed in from get-pipeline-conf
tags_to_download = []
metadata = {}
for line in sys.stdin:
    sys.stdout.write(line.strip() + '\n')
    k, v = line.strip().split('=', 1)

    if k == "TAGS_TO_DOWNLOAD":
        tags_to_download = v.split(',')

    metadata[k] = v

# If we have a set of tags to download we can append our config to the tag as metadata
for tag in tags_to_download:
    taskName = tag.tagData('localhost', 'local', tag.strip(), None, False, False, True, False, metadata)

