#!/bin/bash

set -e

while getopts ":t:l:" option
do
	case "$option" in
		t) tag_name=$OPTARG ;;
		l) acc_ids=$OPTARG ;;
		*) echo "Usage: $0 -t <tag-name> -l <acc_id,acc_id,...>" ;;
	esac
done

if [ -z "$acc_ids" ]; then
	exit 0
fi

my_date=$(date +"%m-%d-%y_%H:%M:%S")
my_date="${my_date}_$$"

mkdir -m 777 -p /mnt/${my_date}

cd /mnt/${my_date}

perl /opt/ergatis/bin/get_genbank_entries.pl --list ${acc_ids}

vp-add-dataset --tag-name ${tag_name} --append --recursive /mnt/${my_date}/

exit $?
