#!/usr/bin/env python
import sys

from vappio.webservice import tag as tag_client

requiredKeys = set(['output.TAGS_TO_DOWNLOAD', 'pipeline.PIPELINE_NAME'])

kv = {}

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

for line in sys.stdin:
    k, v = line.strip().split('=', 1)
    if k in requiredKeys:
        kv[k] = v

missingKeys = requiredKeys - set(kv.keys())
        
if missingKeys:
    raise Exception(str(missingKeys))



pipelineName = kv['pipeline.PIPELINE_NAME']
tags = [pipelineName + '_' + t.strip()
        for t in kv['output.TAGS_TO_DOWNLOAD'].split(',')]


sys.stdout.write('kv\n')

for idx, tag in enumerate(tags):
    if tag_client.listTags('localhost',
                           'local',
                           {'tag_name': tag},
                           False):
        sys.stdout.write('input.TAG%d=%s\n' % (idx, tag))
        
