#!/usr/bin/env python
##
# Takes key-value input and passes it on along with pipeline config
import sys

from vappio.webservice import pipeline

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

# Write our header out
sys.stdout.write('kv\n')

pipelineName = sys.argv[1]

pipelineValues = {}
pl = pipeline.pipelineStatus('localhost', 'local', pipelineName)
for k in pl['config'].keys():
    pipelineValues[k] = str(pl['config'][k])
    
for line in sys.stdin:
    k, v = line.strip().split('=', 1)
    pipelineValues[k] = v


pipelineValues['pipeline.PIPELINE_ID'] = pl['pipeline_id']
    
for k, v in pipelineValues.iteritems():
    sys.stdout.write(str(k) + '=' + str(v).strip().encode('string_escape') + '\n')



