#!/usr/bin/env python
##
# Takes key-value input and passes it on along with pipeline config
import sys

from vappio.webservice import pipeline

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

# Write our header out
sys.stdout.write('kv\n')

pipelineName = sys.argv[1]

pipelineValues = {}
pl = pipeline.pipelineStatus('localhost', 'local', lambda p : p.name == pipelineName)[0]
for k in pl.config.keys():
    pipelineValues[k] = str(pl.config(k))
    
for line in sys.stdin:
    k, v = line.strip().split('=', 1)
    pipelineValues[k] = v


# the following line of code is saved from the previous version in case i mess up - jrw
#sys.stdout.write('\n'.join([k + '=' + str(pl.config(k)).encode('string_escape') for k in pl.config.keys()]) + '\n')
if 'pipeline.PIPELINE_ID' not in pl.config.keys():
    pipelineValues['pipeline.PIPELINE_ID'] = pl.pid
    
for k, v in pipelineValues.iteritems():
    sys.stdout.write(str(k) + '=' + str(v) + '\n')



