#!/usr/bin/env python
##
# Sets pipeline config values.  This only works for pipelines running locally
import sys

from vappio.webservice import pipeline

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

# Write our header out
sys.stdout.write('kv\n')

pl = pipeline.pipelineList('localhost', 'local', {'pipeline_name': sys.argv[1]}, True)[0]

for line in sys.stdin:
    sys.stdout.write(line.strip() + '\n')
    k, v = line.strip().split('=', 1)
    pl['config'][k] = v.decode('string_escape')

pipeline.updatePipelineConfig('localhost', 'local', sys.argv[1], pl['config'])
