#!/usr/bin/env python
##
# Sets pipeline config values.  This only works for pipelines running locally
import sys

from igs.utils import config

from vappio.ergatis import pipeline

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

# Write our header out
sys.stdout.write('kv\n')

pl = pipeline.loadPipeline(sys.argv[1])

kv = {}

for line in sys.stdin:
    k, v = line.strip().split('=', 1)
    if k not in pl.config.keys() or str(pl.config(k)).encode('string_escape') != v:
        kv[k] = v.decode('string_escape')

pl.config = config.configFromMap(kv, pl.config)

pipeline.savePipeline(pl)
