#!/usr/bin/python
import sys

from igs.utils import cli

from vappio.tags import tag_validate

OPTIONS = []

def main(options, _args):
    if sys.stdin.readline().strip() != 'kv':
        raise Exception('Header needs to be kv')

    sys.stdout.write('kv\n')

    tags = []

    for line in sys.stdin:
        sys.stdout.write(line)
        k, v = line.strip().split('=', 1)
        if k.startswith('input.'):
            tags.append(v)

    tag_validate.tags_is_filetype(tags, 'sff')
        
if __name__ == '__main__':
    main(*cli.buildConfigN(OPTIONS))
