---
- hosts: all
  sudo: yes
  gather_facts: yes

  tasks:
    - name: Ensure apt cache is updated.
      apt: >
        update_cache=yes
        cache_valid_time=3600

    - name: Ensure correct kernel headers are installed.
      shell: "apt-get -y install linux-headers-$(uname -r)"

    # SSH daemon configuration.
    - name: Configure SSH daemon.
      lineinfile: >
        dest=/etc/ssh/sshd_config
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
      with_items:
        - { regexp: '^UseDNS', line: 'UseDNS no' }
        - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

    - name: Install basic utilities
      apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim

