#!/bin/bash
sudo apt-get -y install subversion

#Get sourceforge SVN certs because SVN sucks and refuses to let you do this with a command line option
echo p | sudo svn export --force https://svn.code.sf.net/p/vappio/code/trunk/img-conf/root/.subversion /root/.subversion

echo p | sudo svn export --force https://svn.code.sf.net/p/vappio/code/trunk/vappio-install/ /opt/vappio-install

#Update utilities directory if already installed
if [ -d "/opt/vappio-util" ]
then
    /opt/vappio-install/recipes/vappioutil.sh
fi
