#!/bin/bash

##Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh
##

#Run cron every 5 minutes
echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * $vappio_scripts/reaper.sh 2>&1 >> $vappio_runtime/reaper.log" > /etc/cron.d/sgereaper
