#!/bin/bash

##Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh
##

#Run cron every 5 minutes
echo "0,10,20,30,40,50 * * * * root bash $vappio_scripts/reaper.sh >> $vappio_runtime/reaper.log 2>> $vappio_runtime/reaper.log" > /etc/cron.d/sgereaper
