#!/bin/bash

# Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh

vlog "###"
vlog "### $0 (`whoami`)"
vlog "###"

/opt/ergatis/bin/configure_sybil --start_mongo --start_postgres --root_dir=/mnt/ &> /var/log/configure_sybil.build.log
