#!/usr/bin/env python
from igs.utils import cli

from vappio.webservice import credential

OPTIONS = [
    ('host', '', '--host', '', cli.defaultIfNone('localhost')),
    ('cluster', '', '--cluster', '', cli.defaultIfNone('local')),
    ('cred_name', '', '--cred-name', 'Name of the credential', cli.notNone),
    ('dry_run', '-n', '--dry-run', 'Executes a dry run of the pipeline deletion', cli.defaultIfNone(False), cli.BINARY),
    ]

def main(options, _args):
    credential.deleteCredential(options('general.host'),
                                options('general.cluster'),
                                options('general.cred_name'),
                                options('general.dry_run'))

if __name__ == '__main__':        
    main(*cli.buildConfigN(OPTIONS))
