#!/usr/bin/env python

from igs.utils import cli

from vappio.webservice import vm

OPTIONS = []

def main(options, files):
    vmInfo = vm.info()

    print '\t'.join(['RELEASE_NAME', vmInfo['release_name']])
    print '\t'.join(['MAJOR_VERSION', vmInfo['major_version']])
    print '\t'.join(['PATCH_VERSION', str(vmInfo['patch_version'])])
    print '\t'.join(['VM_TYPE', vmInfo['vm_type']])
    print '\t'.join(['SHARED_FOLDERS', 'OK' if vmInfo['shared_folders_enabled'] else 'NOT OK'])

    for p in vmInfo['patches']:
        print '\t'.join(['PATCH', p])
    
if __name__ == '__main__':
    main(*cli.buildConfigN(OPTIONS))
    

