#!/usr/bin/env python
import sys

from twisted.internet import reactor
from twisted.internet import defer

from twisted.python import log

from igs.utils import config
from igs.utils import cli

from igs_tx.utils import defer_utils

from vappio_tx.mq import client


OPTIONS = [
    ('vappio_apps_config',
     '',
     '--config',
     'Path to vappio apps config, defaults to /opt/vappio-apps/vappio_apps.conf',
     cli.defaultIfNone('/opt/vappio-apps/vappio_apps.conf')),
    ('output_file', '', '--output', 'File to dump to', cli.notNone)
    ]


@defer.inlineCallbacks
def _getInfo(options, conf):
    mq = client.connect(conf)
    mq.send('/control/all-messages', options('general.output_file'))
    yield defer_utils.sleep(3)()
    reactor.stop()
    
def main(options, _args):
    log.startLogging(sys.stdout)
    
    conf = config.configFromStream(open(options('general.vappio_apps_config')))

    reactor.callLater(0.0, _getInfo, options, conf)
    reactor.run()


if __name__ == '__main__':
    main(*cli.buildConfigN(OPTIONS))
