#!/usr/bin/env python
from igs.utils import cli

from vappio.webservice import cluster

OPTIONS = [
    ('host', '', '--host', 'Host of webservice to contact', defaultIfNone('localhost')),
    ('cluster', '', '--cluster', 'Name of cluster', notNone),
    ('by_criteria',
     '',
     '--by',
     'Criteria to terminate by [instance_id, public_dns, private_dns, state, instance_type, availability_zone, key, state, ami_id, spot_request_id, bid_price]',
     cli.restrictValues(['instance_id',
                         'public_dns',
                         'private_dns',
                         'state',
                         'instance_type',
                         'availability_zone',
                         'key',
                         'state',
                         'ami_id',
                         'spot_request_id',
                         'bid_price'])),
    ('print_task_name', '-t', '--print-task-name', 'Print the name of the task at the end', cli.defaultIfNone(False), cli.BINARY),
    ]

def main(options, args):
    taskName = cluster.terminateInstances(options('general.host'),
                                          options('general.cluster'),
                                          options('general.by_criteria'),
                                          args)

    if options('general.print_task_name'):
        print taskName
    else:
        runTaskStatus(taskName, clusterName='local')

    

if __name__ == '__main__':
    main(*cli.buildConfigN(OPTIONS))

