#!/bin/bash 
USAGE="vp-auto-test buildvmdir"

timeout=60
hudsonport=8888
buildvm=$1
netcat="clovrtest-lx.igs.umaryland.edu 5678"

for n in `ls $buildvm/shared/clovr-*.runtests`
do
    dname=`dirname $n`
    bname=`basename $n .runtests`
    echo "Running image $dname/$bname"
    #Modify start up process to install hudson
    mkdir $dname/$bname/shared/user-scripts || true
    chmod 777 $dname/$bname/shared/user-scripts || true
    #ln -s /opt/vappio-install/recipes/hudson.sh $dname/$bname/shared/user-scripts/01-installhudson || true
    echo "#!/bin/bash" > $dname/$bname/shared/user-scripts/02-starthudson
    echo "/etc/init.d/hudson start" >> $dname/$bname/shared/user-scripts/02-starthudson
    chmod a+rx $dname/$bname/shared/user-scripts/02-starthudson
    #TODO - set 24hr shutdown
    
    #Boot the image
    /home/sangiuoli/vp-launch-headless $dname/$bname vmware || true
    nipaddr=`cat $dname/$bname/shared/clovr_ip`
    
    #Launch the tests
    curl --silent http://$nipaddr:$hudsonport > /dev/null
    if [ $? != 0 ]
    then
	echo "Waiting for hudson to start"
	sleep 30 #wait for hudson to start
	curl --silent http://$nipaddr:$hudsonport > /dev/null
	if [ $? != 0 ]
	    then
	    echo "Hudson not found at $nipaddr:$hudsonport"
	fi
    fi
    for t in `cat $n`
      do
      curl --silent http://$nipaddr:$hudsonport/job/$t/build
      if [ $? = 0 ]
      then
	  if [ "$netcat" != "" ]
	  then
	  echo "Automated tests $t for $bname started at http://$nipaddr:8888/" | nc $netcat || true
	  fi
	  rm $n
      fi
    done
done
