#!/bin/bash

USAGE="vp-autobuild [buildvm]"
hudsonport=8888

if [ "$1" = "" ]
then
    buildvm="/data/sangiuoli/clovr-base-20100827-3"
else
    buildvm=$1
fi

#Check if buildvm is running
if [ -d "$buildvm/start_clovr.vmx.lck" ]
then
    echo "VM $buildvm is already running"
else
    mkdir $buildvm/shared/user-scripts
    chmod 777 $buildvm/shared/user-scripts
    echo "#!/bin/bash" > $buildvm/shared/user-scripts/01-starthudson
    echo "/etc/init.d/hudson start" > $buildvm/shared/user-scripts/01-starthudson
    chmod a+rx $buildvm/shared/user-scripts/01-starthudson
    vp-launch-headless $buildvm vmware
    sleep 10 #wait for hudson to finish booting
fi

ipaddr=`cat $buildvm/shared/clovr_ip`

#Check for hudson
curl http://$ipaddr:$hudsonport > /dev/null
if [ $? != 0 ]
then
    echo "Hudson not found at $ipaddr:$hudsonport"
    exit 1;
fi

ls $buildvm/shared/clovr-*.tgz > /tmp/$$.builds

#Check if build in progress
buildinprogress=`curl http://$ipaddr:$hudsonport/view/Platform%20conversion/rssLatest | xpath -e '//entry/title/text()'  | grep "Build all bundle image" | grep "(null)"`
if [ $buildinprogress != "" ]
then
    echo "Build in progress at http://$ipaddr:8888"
    echo "Ignoring these builds for launching new tests"
    cat /tmp/$$.builds
else
#Launch hudson builds
    echo "Launching build all at http://$ipaddr:8888"
    curl http://$ipaddr:8888/job/Build\%20all\%20bundle\%20image/build
fi

ls $buildvm/shared/clovr-*.tgz > /tmp/$$.newbuilds
diff=`diff /tmp/$$.builds /tmp/$$.newbuilds`
while [ "$diff" = "" ] 
do
    echo -n "."
    sleep 60
    ls $buildvm/shared/clovr-*.tgz > /tmp/$$.newbuilds
done
#Launch hudson tests
newbundles=`diff /tmp/$$.builds /tmp/$$.newbuilds | grep ">" | perl -ne 's/\>\s+//;s/\.tgz$//;print'`
for $n $newbundles
do
    #Modify start up process to install hudson
    mkdir $n/shared/user-scripts
    chmod 777 $n/shared/user-scripts
    ln -s /opt/vappio-install/recipes/hudson.sh $n/shared/user-scripts/01-installhudson
    echo "#\!/bin/bash" > $n/shared/user-scripts/02-starthudson
    echo "/etc/init.d/hudson start" > $n/shared/user-scripts/02-starthudson
    chmod a+rx $n/shared/user-scripts/01-starthudson
    #TODO - set 24hr shutdown
    
    #Boot the image
    ~/vp-launch-headless $n vmware
    nipaddr=`cat $n/shared/clovr_ip`
    sleep 10 #wait for hudson to start

    #Launch the tests
    curl http://$nipaddr:$hudsonport > /dev/null
    if [ $? != 0 ]
    then
	echo "Hudson not found at $nipaddr:$hudsonport"
    else
	curl http://$ipaddr:8888/job/00\%20Launch\%20all\%20jobs/build
    fi
    
done

##SCRATCH
#for imgname `ls $newimagesdir`
#do
#    VBoxManage list runningvms | grep $imgname
#    if [ $? != 0 ]
#    then
	#Import and Launch
#	VBoxMange import $imgname/$imgname.ovf
	#Launch
#	VBoxHeadless --startvm $imgname --vrdp=off
	#Set up shared folders
	
	#Read shared/clovr_ip and announce
#done