#!/bin/bash

USAGE="vp-autobuild [buildvm]"
hudsonport=8888

if [ "$1" = "" ]
then
    buildvm="/data/clovr-build"
else
    buildvm=$1
fi

#Check if buildvm is running
if [ -d "$buildvm/start_clovr.vmx.lck" ]
then
    echo "VM $buildvm is already running"
else
    mkdir $buildvm/shared/user-scripts
    chmod 777 $buildvm/shared/user-scripts
    echo "#!/bin/bash" > $buildvm/shared/user-scripts/01-starthudson
    echo "/etc/init.d/hudson start" >> $buildvm/shared/user-scripts/01-starthudson
    chmod a+rx $buildvm/shared/user-scripts/01-starthudson
    ~/vp-launch-headless $buildvm vmware
    sleep 10 #wait for hudson to finish booting
fi

ipaddr=`cat $buildvm/shared/clovr_ip`

#Check for hudson
curl --silent http://$ipaddr:$hudsonport > /dev/null
if [ $? != 0 ]
then
    echo "Hudson not found at $ipaddr:$hudsonport"
    exit 1;
fi

#Check if build in progress
buildinprogress=`curl --silent http://$ipaddr:$hudsonport/view/Platform%20conversion/rssLatest | xpath -e '//entry/title/text()'  | grep "Build all bundle image" | grep "(null)"`
if [ "$buildinprogress" != "" ]
then
    echo "Build in progress at http://$ipaddr:8888"
else
#Launch hudson builds
    echo "Launching build all at http://$ipaddr:8888"
    curl --silent http://$ipaddr:8888/job/Build\%20all\%20bundle\%20image/build
fi


##SCRATCH
#for imgname `ls $newimagesdir`
#do
#    VBoxManage list runningvms | grep $imgname
#    if [ $? != 0 ]
#    then
	#Import and Launch
#	VBoxMange import $imgname/$imgname.ovf
	#Launch
#	VBoxHeadless --startvm $imgname --vrdp=off
	#Set up shared folders
	
	#Read shared/clovr_ip and announce
#done