#!/bin/bash

USAGE="vp-bundle-ovf [-z] [-s] image.vmdk name outputprefix sharedpath\n
Converts image.vmdk to Virtualbox compatible formats.\n
An OVF file with $outputprefix.ovf with embedded VM $name\n
A VDI file with outputprefix.vdi\n
-s skip creation of VDI file\n
-z compress vdi
"

while getopts "hzs" options; do
  case $options in
      z ) compress=1
	  shift
	  ;;
      s ) skipvdi=1
	  shift
	  ;;
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

rm -rf /root/.VirtualBox
rm -rf /mnt/.VirtualBox
mkdir -p /mnt/.VirtualBox
ln -f -s /mnt/.VirtualBox /root/.VirtualBox

#Clean up any old vms with the same name

VBoxManage -q closemedium disk $1
VBoxManage -q unregistervm $2 

rm -rf ~/.VirtualBox/Machines/$2

VBoxManage -q createvm --name $2 --register

VBoxManage -q modifyvm $2 --ostype "Ubuntu_64" --memory 2048 --boot1 disk --nic1 bridged

#VBoxManage -q storagectl $2 --name "IDE Controller" --add ide
#VBoxManage -q storageattach $2 --storagectl "IDE Controller" --port 0 --device 0 --type hdd --medium $1
echo "Attaching SATA drive"
VBoxManage -q storagectl $2 --name "SATA Controller" --add sata --controller IntelAhci
VBoxManage -q storageattach $2 --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $1

#Not certain this is portable
echo "Attaching network device"
VBoxManage -q modifyvm $2 --nic1 bridged --bridgeadapter1 "en0:Ethernet"

if [ "$4" != "" ]
then
    echo "Specifying shared folders"
    VBoxManage sharedfolder add $2 --name shared --hostpath $4/shared/ 
    VBoxManage sharedfolder add $2 --name keys --hostpath $4/keys/ 
    VBoxManage sharedfolder add $2 --name user_data --hostpath $4/user_data/
    VBoxManage sharedfolder add $2 --name pg_data --hostpath $4/pg_data/
fi

echo "Creating ovf"
#Create ovf
rm -rf $3
VBoxManage export $2 -o $3.ovf

if [ "$skipvdi" = "" ]
then
#To create VDI
    echo "Creating vdi"
    #vdibname=`basename $1`
    #vdidirname=`dirname $1`
    vdibname=$2
        
    #VBoxManage -q closemedium disk $1
    VBoxManage internalcommands sethduuid $1
    
    #rm -f /root/.VirtualBox/HardDisks/$vdibname.vdi
    VBoxManage createhd --filename $vdibname.vdi --size 120000 --format vdi
    VBoxManage clonehd --existing $1 $vdibname.vdi 
    if [ "$compress" != "" ]
    then
	echo "Compressing vdi"
	gzip $vdibname.vdi
    fi
fi

#To automatically import
#rm -rf /root/.Virtualbox
#mkdir /mnt/.Virtualbox
#ln -s /mnt/.Virtualbox /root/.Virtualbox
#VBoxManage internalcommands sethduuid $1
#VBoxManage import $3
