#!/bin/bash -e

USAGE="vp-bundle-ec2 [-p] [-f] [-k kernel AKI] image.img|imagedir\n
Bundles and uploads an AMI of image.img\n
Requires authentication information in the following files\n
/mnt/keys/ec2user, /mnt/keys/ec2account, /mnt/keys/ec2secretkey, /mnt/keys/pk-XXX.pem, /mnt/keys,cert-XXX.pem\n
Use -p to make the image public\n
Use -f to force rebundle and upload even if the bucket already exists\n
If a directory imagedir is specified, looks for imagedir.img and attempts to write AMI to imagedir/clovr.conf
Will tar imagedir upon successful completion
"

aki=aki-0b4aa462 #default kernel Ubuntu 10
public=0
i=0
while getopts "fph" options; do
  case $options in
    p ) public=1
	  i=`expr $i + 1`
	  ;;
    h ) echo -e $USAGE
	  exit 1;;
    f ) force="force"
	  i=`expr $i + 1`
	  ;;
    \? ) echo -e $USAGE
         exit 1;;
  esac
done
for (( c=1; c<=$i; c++ ))
do
    shift
done

if [ -d "$1" ]
then
    imagedir=$1
    image="$1.img"
else
    image=$1
fi

if [ ! -f "$image" ]
then
    echo "Can't find image $image"
    echo "$USAGE"
    exit 1
fi
if [ ! -f "/mnt/keys/ec2user" ] || [ ! -f "/mnt/keys/ec2account" ] || [ ! -f "/mnt/keys/ec2secretkey" ] || [ ! -f "/mnt/keys/ec2pk" ] || [ ! -f "/mnt/keys/ec2cert" ]
then
    echo "Save ec2 keys and account information in /mnt/keys"
    echo "Files: ec2user,ec2account,ec2secretkey,ec2pk,ec2cert"
    echo "ec2pk and ec2cert should list path to files pk-XXX.pem and cert-XXX.pem on the image"
    exit 2
fi

imgname=`basename $1`

#Assumes running on a clovr build image
source /opt/vappio-scripts/clovrEnv.sh
export EC2_HOME=/opt/ec2-ami-tools-1.3-56066
export EC2_AMITOOL_HOME=/opt/ec2-ami-tools-1.3-56066

user=`cat /mnt/keys/ec2user`
account=`cat /mnt/keys/ec2account`
secretkey=`cat /mnt/keys/ec2secretkey`
ec2pk=`cat /mnt/keys/ec2pk`
ec2cert=`cat /mnt/keys/ec2cert`

#A temp directory
mkdir -p /mnt/ec2bundles$$

if [ -f "/mnt/ec2bundles$$/$imgname.manifest.xml" ] || [ "$force" != "force" ]
then
    echo "Found manifest, /mnt/ec2bundles$$/$imgname.manifest.xml, skipping ec2-bundle-image"
else
    echo "Bundling image $imgname"
    $EC2_AMITOOL_HOME/bin/ec2-bundle-image -c $ec2cert -k $ec2pk -u $user --kernel $aki -i $image -d /mnt/ec2bundles$$ -p $imgname -r x86_64
fi

#If not Access Denied, bucket does not exist
s3manifest=`curl --silent http://s3.amazonaws.com/$imgname | grep Access` || true
if [ "$s3manifest" = "" ] || [ "$force" = "force" ]
then
    #Upload bundle
    echo "Uploading $imgname to S3"
    $EC2_AMITOOL_HOME/bin/ec2-upload-bundle -b $imgname -m /mnt/ec2bundles$$/$imgname.manifest.xml -a $account -s $secretkey
fi

export EC2_HOME=/opt/opt-packages/ec2-ami-tools-1.3-57676/
export EC2_APITOOL_HOME=/opt/opt-packages/ec2-ami-tools-1.3-57676/
export JAVA_HOME=/usr
echo "Registering on EC2 $imgname/$imgname.manifest.xml"
ami=`$EC2_APITOOL_HOME/bin/ec2-register $imgname/$imgname.manifest.xml -K $ec2pk -C $ec2cert -n $imgname | perl -ne '/^IMAGE\s+(ami-\S+)/;print $1,"\n"'`
echo "AMI: $ami"

#Mark public 
if [ "$public" = 1 ]
then
    $EC2_APITOOL_HOME/bin/ec2-modify-image-attribute -C $ec2cert -K $ec2pk $ami --launch-permission -a all
fi

#Set AMI in clovr.conf if this is a clovr image
if [ -d "$imagedir" ] && [ -f "$imagedir/shared/vappio-conf/clovr.conf" ]
then
    echo "Writing $ami to $imagedir/clovr.conf"
    perl -pi -e "s/^ami=.*/ami=$ami/" $imagedir/shared/vappio-conf/clovr.conf
fi
echo "Bundled and uploaded AMI: $ami"

#cleanup
rm -rf /mnt/ec2bundles$$

