#!/bin/bash
#Packages a raw disk image as a vmdk for VMware and VirtualBox

#Without force, will resume using an existing vmdk named
#image.img.vmdk. force remakes a vmdk even if one already exists

USAGE="vp-bundle-release image.img name [force]"

while getopts "h" options; do
  case $options in
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

currimg=$1
namepfx=$2
force=$3

recipedir=/opt/vappio-install/recipes
utildir=/opt/vappio-util
vmxtemplate=/mnt/start_clovr.tmpl.vmx
sharedtemplate=https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/img-conf/mnt/shared

if [ "$force" != "" ] || [ ! -e $currimg.vmdk ]
then
    wget -c -P /mnt http://cb2.igs.umaryland.edu/grub-boot.tgz
    svn export --force  https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/img-conf/boot /mnt/boot
    pushd /mnt
    tar cvzf grub-boot.tgz boot
    popd
    
    cp --sparse=always $currimg $currimg.vmbundle
    $utildir/vp-runonimg $currimg.vmbundle $recipedir/vmware.sh
    $utildir/vp-runonimg $currimg.vmbundle $recipedir/vbox.sh
    $utildir/vp-runonimg $currimg.vmbundle $utildir/cleanupimg
    
    $utildir/vp-create-vmdk $currimg.vmbundle /mnt/grub-boot.tgz $currimg.vmdk
    echo "Created $currimg.vmdk"
    rm -rf $currimg.vmbundle
fi
mkdir $namepfx
chmod 777 $namepfx
pushd $namepfx
#Create ovf bundle
$utildir/vp-bundle-ovf $currimg.vmdk $namepfx $namepfx.ovf /clovr/$namepfx

#Add vmx file
#svn export --force https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/util/start_clovr.vmx /mnt/start_clovr.tmpl.vmx
svn export --force $vmxtemplate /mnt/vmx$$.tmpl.vmx
$utildir/vp-bundle-vmx ".\/$namepfx.vmdk" /mnt/vmx$$.tmpl.vmx start_clovr.vmx $namepfx

#Add shared folder 
#svn export --force https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/img-conf/mnt/shared shared
svn export --force $sharedtemplate shared

chmod 777 shared
mkdir keys
chmod 777 keys
mkdir user_data
chmod 777 user_data
popd
#The OVF export will create a vmdk file but VMware 
#will not mount rw and throws write errors, ata1 drdy err indf
echo "Moving $currimg.vmdk $namepfx/$namepfx.vmdk"
mv $currimg.vmdk $namepfx/$namepfx.vmdk

currimgbname=`basename $currimg`
rm $namepfx/$currimgbname.vmdk

perl -pi -e "s/href=\".*\.vmdk\"/href=\"$namepfx.vmdk\"/" $namepfx/$namepfx.ovf
chmod 777 $namepfx
#Manifest file may cause problems on import
rm -f $namepfx/$namepfx.mf
sync

#Need to ignore errors from tar due to sparse files
#echo "Creating tar $namepfx.tgz"
#Sparse files cause compat problems on windows
#tar -S -cvzf $namepfx.tgz $namepfx || true
#tar -cvzf $namepfx.tgz $namepfx || true

#Zip does not support large files and 7z does not preserve file permissions
#zip -r $namepfx.zip $namepfx