#!/bin/bash

USAGE="vp-bundle-release [-f] [-t] image.img releasename\n
Creates release-ready VMware (vmdk,vmx) and Virtualbox (ovf,vdi) VMs from a raw disk image, image.img\n
-f force remakes a vmdk even if one already exists. Default is resume using an existing vmdk\n
-t Bundle guest tools for VMware and VirtualBox. Off by default.\n
"

while getopts "tfh" options; do
  case $options in
      t ) bundletools=1
	  shift
	  ;;
      f ) force=1
	  shift
	  ;;
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

currimg=$1
namepfx=$2

recipedir=/opt/vappio-install/recipes
utildir=/opt/vappio-util
vmxtemplate=https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/util/start_clovr.vmx
sharedtemplate=https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/img-conf/mnt/shared

if [ "$force" != "" ] || [ ! -e $currimg.vmdk ]
then
    wget -c -P /mnt http://cb2.igs.umaryland.edu/grub-boot.tgz
    svn export --force  https://vappio.svn.sourceforge.net/svnroot/vappio/trunk/img-conf/boot /mnt/boot
    pushd /mnt
    tar cvzf grub-boot.tgz boot
    popd
    
    cp --sparse=always $currimg $currimg.vmbundle
    if [ "$bundletools" != "" ]
    then
	$utildir/vp-runonimg $currimg.vmbundle $recipedir/vmware.sh
	$utildir/vp-runonimg $currimg.vmbundle $recipedir/vbox.sh
    fi
    $utildir/vp-runonimg $currimg.vmbundle $utildir/cleanupimg
    
    $utildir/vp-create-vmdk $currimg.vmbundle /mnt/grub-boot.tgz $currimg.vmdk
    echo "Created $currimg.vmdk"
    rm -rf $currimg.vmbundle
fi
mkdir $namepfx
chmod 777 $namepfx
pushd $namepfx
#Create ovf bundle
$utildir/vp-bundle-ovf -z $currimg.vmdk $namepfx `pwd` /clovr/$namepfx

#Add vmx file
svn export --force $vmxtemplate /mnt/vmx$$.tmpl.vmx
$utildir/vp-bundle-vmx ".\/$namepfx.vmdk" /mnt/vmx$$.tmpl.vmx start_clovr.vmx $namepfx

#Add shared folder 
svn export --force $sharedtemplate shared

chmod 777 shared
mkdir keys
chmod 777 keys
mkdir user_data
chmod 777 user_data
popd
#The OVF export will create a vmdk file but VMware 
#will not mount rw and throws write errors, ata1 drdy err indf
echo "Moving $currimg.vmdk $namepfx/$namepfx.vmdk"
mv $currimg.vmdk $namepfx/$namepfx.vmdk

currimgbname=`basename $currimg`
rm -f $namepfx/$currimgbname.vmdk

perl -pi -e "s/href=\".*\.vmdk\"/href=\"$namepfx.vmdk\"/" $namepfx/$namepfx.ovf
chmod 777 $namepfx
#Manifest file may cause problems on import
rm -f $namepfx/$namepfx.mf
sync

#Need to ignore errors from tar due to sparse files
#echo "Creating tar $namepfx.tgz"
#Sparse files cause compat problems on windows
#tar -S -cvzf $namepfx.tgz $namepfx || true
#tar -cvzf $namepfx.tgz $namepfx || true

#Zip does not support large files and 7z does not preserve file permissions
#zip -r $namepfx.zip $namepfx
