#!/bin/bash

#USAGE:./vp-compress-img image.img image.img.tgz
#Requires you are in the same directory as image.img

mkdir -p /mnt/$$
devname=`losetup --show -f $1`
mount $devname /mnt/$$
dd if=/dev/zero of=/mnt/$$/tmp/ZEROS > /dev/null 2> /dev/null
rm /mnt/$$/tmp/ZEROS
umount /mnt/$$ 
rm -rf /mnt/$$
losetup -d $devname
chmod 666 $1
fname=`basename $1`
dname=`dirname $1`
pushd $dname
#Sparse files cause compatibility problems on windows
tar -S -cvzf $2 $fname || true
popd

