#!/bin/bash

#USAGE:./vp-compress-img image.img image.img.tgz

mkdir /mnt/foo1
losetup -f $1
mount /dev/loop0 /mnt/foo1
dd if=/dev/zero of=/mnt/foo1/tmp/ZEROS
rm /mnt/foo1/tmp/ZEROS
umount /mnt/foo1 
rm -rf /mnt/foo1
losetup -d /dev/loop0
fname=`basename $1`
tar -S -cvzf $2 $1


