#!/bin/bash

#Capture output to diagnostic file
exec 3>&1 4>&2 >/tmp/vp-diagnostic.$$.out 2>&1

echo "##report $$"

cat /etc/vappio/*.info 

echo "##node_type"

cat /var/vappio/runtime/cloud_type
cat /var/vappio/runtime/node_type

echo "##dns"
ls /var/vappio/runtime/no_dns

echo "##hostname"

hostname -f

echo "##folders"

/opt/vappio-metrics/check-sharedfolders
df
mount

echo "##networking"

ifconfig

echo "##reachable"

printf "kv\nhostname=`hostname`\n" | /opt/vappio-metrics/host-is-reachable

echo "##qstat"

qstat -u '*'

echo "##qhost -q -j"

qhost -q -j

echo "##vp-describe-credentials"

vp-describe-credentials

echo "##vp-describe-pipelines"

vp-describe-pipeline

echo "##vp-describe-task"

vp-describe-task

echo "##vp-describe-dataset"

vp-describe-dataset

echo "##machine conf"

cat /tmp/machine.conf

echo "##vappio start log"

cat /tmp/vappio.log

echo "##vappio log"

cat /var/log/vappio.log*

echo "##webservices log"

cat /tmp/webservices.log

echo "##vmstatus log"

cat /tmp/vmStatus.log

echo "##startup log"

cat /tmp/startUpNode.log

echo "##ergatisObserver"

cat /tmp/ergatisObserver.log

echo "##kernel"

uname -a

echo "##lsmod"

lsmod

#Email diagnostic file

#We must post this to a form on clovr.org. Mail is blocked from some domains such as Comcast
if [ "$1" == "" ]
then
    name="unknown"
else	
    name="$1"
fi

echo "##Submit"
cmd="curl -F \"token=yuQ9UWZWLspxPkV1w4BT\" -F \"name=$name\" -F \"data=</tmp/vp-diagnostic.$$.out\" http://clovr.org/diagnostics/index.php"
echo $cmd
curl -F "token=yuQ9UWZWLspxPkV1w4BT" -F "name=$name" -F "data=</tmp/vp-diagnostic.$$.out" http://clovr.org/diagnostics/index.php

exec 1>&3 2>&4
echo "Diagnostic report $$ completed and submitted."
