#!/bin/bash

#Launch a VM in headless mode and return the IP address
USAGE="vp-launch-headless [vm_bundle_directory] [vmware|vbox]"
#

if [ -d "$1" ] && [ -f $1/start_clovr.vmx ]
then
    echo "Starting VM in $1"
else
    echo $USAGE
    exit 1
fi

if [ -d "$1/start_clovr.vmx.lck" ]
then
    echo "VM $buildvm is already running"
    exit 1
else
    xhost + 
    xhost +LOCAL:
    export DISPLAY=:0.0
    
    if [ "$2" = "vbox" ]
    then
    #TODO, implement
	VBoxManage
    else
	vmplayer $1/start_clovr.vmx &
    fi
    
    ipstat=`stat -t $1/shared/clovr_ip`
    ipstatnew=`stat -t $1/shared/clovr_ip`
    timeout=60 #5 minutes
    count=1
    while [ "$ipstat" = "$ipstatnew" ]
    do
	echo -n "."
	ipstatnew=`stat -t $1/shared/clovr_ip`
	sleep 5
	count=`expr $count + 1`
	if [ $count -gt $timeout ]
	then
	    echo "Machine boot not detected, exiting"
	    exit 1;
	fi
    done
    
    echo 
    cat $1/shared/clovr_ip
fi