#!/bin/bash

USAGE="vp-runonvdi image.vdi cmd [partition]\n
Runs cmd on image.vdi\n
Equivalent to\n
chroot image.vdi cmd\n
"
while getopts "h" options; do
  case $options in
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

#Mounts image as loopback, copies CMD onto the image and runs

echo "Attempting to mount $1"

rm -rf /mnt/vfuse_$$
mkdir /mnt/vfuse_$$
vdfuse -f $1 /mnt/vfuse_$$

#Use user provided logical partition number if available
if [ "$3" == "" ]
then
    partition="Partition1"
else
    partition="Partition$3"
fi
echo "Mounting $partition"

devname=`losetup --show -f /mnt/vfuse_$$/$partition`

rm -rf /mnt/$$
mkdir /mnt/$$
mount $devname /mnt/$$

if [ -e "/mnt/$$/proc" ]
then
    mount -t proc none /mnt/$$/proc
    mount --bind /sys /mnt/$$/sys
    mount --bind /dev /mnt/$$/dev 
    #copy command onto the image
    bname=`basename $2`
    cp $2 /mnt/$$/tmp/$bname
    chmod +x /mnt/$$/tmp/$bname || true
    #Run the command
    chroot /mnt/$$ /tmp/$bname
else
    pushd /mnt/$$
    $2
    popd
fi

sync

if [ -e "/mnt/$$/proc" ]
then
    umount -l /mnt/$$/proc
    umount -l /mnt/$$/sys
    umount -l /mnt/$$/dev
fi
sleep 3

umount -l /mnt/vfuse_$$
umount -l /mnt/$$

rmdir /mnt/vfuse_$$
rmdir /mnt/$$

losetup -d $devname

exit
