#!/bin/bash

USAGE="vp-runonimg image.img cmd\n
Runs cmd on image.img\n
Equivalent to\n
chroot image.img cmd\n
"
while getopts "h" options; do
  case $options in
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

#Mounts image as loopback, copies CMD onto the image and runs

devname=`losetup --show -f $1`
rm -rf /mnt/$$
mkdir /mnt/$$

mount $devname /mnt/$$
#mount --bind /proc /mnt/$$/proc
mount -t proc none /mnt/$$/proc
mount --bind /sys /mnt/$$/sys
mount --bind /dev /mnt/$$/dev

#copy command onto the image
bname=`basename $2`
cp $2 /mnt/$$/tmp/$bname
chmod +x /mnt/$$/tmp/$bname || true
#Run the command
chroot /mnt/$$ /tmp/$bname

sync

umount -l /mnt/$$/proc
umount -l /mnt/$$/sys
umount -l /mnt/$$/dev
umount -l /mnt/$$

rmdir /mnt/$$

losetup -d $devname

exit
