#!/bin/bash 

##Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh
##

do_start() {
##
#To support ad-hoc virtual clusters, 
#set up mock hostname if we don't have one, using the clovr-IPADDR naming convention
#This is required so that SGE can run locally without problems
    nodns=0
    cp /etc/hosts.orig /etc/hosts
    myhostname=`hostname -f`
    #Simple check to see if there is DNS
    if [ $? != "0" ] 
    then
	echo "Detected no DNS"
	nodns=1
    else
	clovrhostname=`echo $myhostname | grep clovr-`
	if [ "$clovrhostname" != "" ]
	then
	    echo "Detected no DNS, clovr hostname"
	    nodns=1
	else
	    localhostname=`echo $myhostname | grep localhost`
	    if [ "$localhostname" != "" ]
	    then
		echo "Detected no DNS, localhostname"
		nodns=1
	    else
		ping -c 1 $myhostname
		if [ $? != "0" ]
		then
		    nodns=1
		fi
	    fi
	fi
    fi
    #There appears to be no DNS at boot
    if [ $nodns = "1" ]
    then
	if [ "$2" = "" ]
	then
	    ipaddr=`/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print ""$2"" }'`
	else
	    ipaddr=$2
	fi
	if [ "$ipaddr" = "" ]
	then
	    ipaddr="127.0.0.1"
	    ipalias=`echo $ipaddr | sed -e 's/\./-/g'`;
	    #Set as the only line in the file
	    echo "$ipaddr clovr-$ipalias clovr-$ipalias" > /etc/hosts
	else
	    cp /etc/hosts.orig /etc/hosts
	    ipalias=`echo $ipaddr | sed -e 's/\./-/g'`;
	    echo "$ipaddr clovr-$ipalias clovr-$ipalias" >> /etc/hosts
	fi
	echo "Attempting to set hostname clovr-$ipalias"
	hostname clovr-$ipalias
	#If vappio is installed, mark no_dns
	if [ -d "/var/vappio/runtime" ]
	then
	    touch $vappio_runtime/no_dns
	fi
    fi

    #Set MAC address in dhclient.conf
    export macaddr=`ifconfig -a | perl -ne 'if(/^eth0.*HWaddr\s+(\S+)/){print $1}'`
    if [ "$macaddr" != "" ]
    then
	perl -pi -e 's/^send\s+dhcp-client-identifier\s+(\S+)/send dhcp-client-identifier "$ENV{macaddr}";/' /etc/dhcp3/dhclient.conf
    fi
    #Open permissions on /etc/hosts for web services
    chmod a+rw /etc/hosts
}

do_stop() {
    cp /etc/hosts.orig /etc/hosts
}

case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart)
	do_stop
	do_start
	;;
    *)
	echo $"Usage: $0 {start|stop} [ipaddr]"
	exit 1
esac

exit $?
