#!/bin/bash 

do_start() {
##
#To support ad-hoc virtual clusters, 
#set up mock hostname if we don't have one, using the clovr-IPADDR naming convention
#This is required so that SGE can run locally without problems
    nodns=0
    cp /etc/hosts.orig /etc/hosts
    myhostname=`hostname -f`
    #Simple check to see if there is DNS
    if [ $? != "0" ]
    then
	nodns=1
    else
	clovrhostname=`echo $myhostname | grep clovr-`
	if [ "$clovrhostname" != "" ]
	then
	    nodns=1
	else
	    localhostname=`echo $myhostname | grep localhost`
	    if [ "$localhostname" != "" ]
	    then
		nodns=1
	    else
		ping -c 1 $myhostname
		if [ $? != "0" ]
		then
		    nodns=1
		fi
	    fi
	fi
    fi
    #There appears to be no DNS at boot
    if [ $nodns = "1" ]
    then
	ipaddr=`/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print ""$2"" }'`
	if [ "$ipaddr" = "" ]
	then
	    ipaddr="127.0.0.1"
	    ipalias=`echo $ipaddr | sed -e 's/\./-/g'`;
	    #Set as the only line in the file
	    echo "$ipaddr clovr-$ipalias clovr-$ipalias" > /etc/hosts
	else
	    cp /etc/hosts.orig /etc/hosts
	    ipalias=`echo $ipaddr | sed -e 's/\./-/g'`;
	    echo "$ipaddr clovr-$ipalias clovr-$ipalias" >> /etc/hosts
	fi
	echo "Attempting to set hostname clovr-$ipalias"
	hostname clovr-$ipalias
	echo "$ipaddr" > /mnt/clovr_ip
	#If vappio is installed, mark no_dns
	if [ -f "/var/vappio/runtime" ]
	then
	    vappio_scripts=/opt/vappio-scripts
	    . $vappio_scripts/vappio_config.sh
	    touch $vappio_runtime/no_dns
	fi
    fi
}

do_stop() {
    cp /etc/hosts.orig /etc/hosts
}

case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart)
	do_stop
	do_start
	;;
    *)
	echo $"Usage: $0 {start|stop}"
	exit 1
esac

exit $?
