#!/usr/bin/env python
# Takes the number of CPU hours and outputs the number of files for a blast run
#
# Required keys:
# pipeline.COMPUTED_CPU_HOURS
#
# Output keys:
# parameters.TOTAL_FILES
#
# All other kv pairs are passed through
import sys

# Ensure we are dealing with kv pairs
if sys.stdin.readline().strip() != 'kv':
    raise Exception('Header needs to be kv')

# Write our header out
sys.stdout.write('kv\n')

requiredKeys = ['pipeline.COMPUTED_CPU_HOURS']

kv = {}

for line in sys.stdin:
    sys.stdout.write(line.strip() + '\n')
    k, v = line.strip().split('=', 1)
    kv[k] = v

if set(requiredKeys) - set(kv.keys()):
    raise Exception('Not all required keys present')

cpuHours = kv['pipeline.COMPUTED_CPU_HOURS']

sys.stdout.write('\n'.join(['parameters.TOTAL_FILES=' + str(int(float(cpuHours) * 3)),
                            'parameters.SEQS_PER_FILE=']) + '\n')
