#!/bin/bash

if [ -f "/var/vappio/runtime/node_type" ]
then
    mirrorlogs=0
    vappio_scripts=/opt/vappio-scripts
    source $vappio_scripts/vappio_config.sh
    
    nodetype=`cat $vappio_runtime/node_type`
    
    if [ "$reason" = "BOUND" ] 
    then
	vlog "DHCP new address $new_ip_address"
	if [ "$nodetype" != "PENDING" ] 
	then
	    old_ip_address=`cat /mnt/clovr_ip`
	    if [ "$new_ip_address" != "$old_ip_address" ]
	    then
		vlog "DHCP returned new address $new_ip_address, old address $old_ip_address"
		vlog "DHCP change, forcing removal of current host `hostname -f` from SGE"
	        #Reset hostname
		/etc/init.d/hostnamecheck start $new_ip_address	    
		vlog "DHCP change, reset hostname to SGE"
		echo "$new_ip_address" > /mnt/clovr_ip
	        #This can take a few minutes
		#Detect node types
		platform=`/etc/vappio/vp-detect-platform`
		if [ -e "/etc/vappio/$platform/vp-detect-nodetype" ]
		then	 
		    nodetype=`/etc/vappio/$platform/vp-detect-nodetype` 
		else
		    echo "Skipping node type detection for platform. Using default node type"
		    nodetype="master"
		fi
		$vappio_scripts/vp-start-node $nodetype
		#TODO, move this to /etc/vappio startup sequence
		/opt/vappio-py/vappio/cli/createLocalMachineConf.py --conf=/mnt/vappio-conf/clovr_base.conf -o /tmp/machine.conf
		/opt/vappio-py/vappio/cli/remote/startUpNode.py
	    else
		vlog "DHCP, same address as previous. skipping reset"
	    fi
	else
	    vlog "DHCP, node is $nodetype, skipping reset"
	fi
    fi
fi
