#!/bin/bash

if [ -f "/var/vappio/runtime/node_type" ]
then
    vappio_scripts=/opt/vappio-scripts
    source $vappio_scripts/vappio_config.sh
    
    nodetype=`cat $vappio_runtime/node_type`
    
    if [ "$reason" = "BOUND" ] && [ "$nodetype" != "PENDING" ] && [ "$nodetype" != "OFFLINE" ] && [ "$nodetype" != "" ]
    then
	old_ip_address=`cat /mnt/clovr_ip`
	if [ "$new_ip_address" != "$old_ip_address" ]
	then
	    vlog "DHCP returned new address $new_ip_address, old address $old_ip_address"
	    vlog "DHCP change, forcing removal of current host `hostname -f` from SGE"
	    /opt/vappio-scripts/remove_sgehost.sh `hostname -f`
	    #Reset hostname
	    /etc/init.d/hostnamecheck start $new_ip_address	    
	    vlog "DHCP change, reset hostname to SGE"
	    echo "$ipaddr" > /mnt/clovr_ip
	    #This can take a few minutes
	    $vappio_scripts/vp-restart-node
	fi
    fi
fi
