#!/usr/bin/env python

import sys

from igs.config_manage.policy import *

if len(sys.argv) < 2:
    raise Exception('Must provide start|stop|restart')

if sys.argv[1] == 'start':
    executeTemplate('/etc/hadoop/conf/core-site.xml.tmpl')
    executeTemplate('/etc/hadoop/conf/hdfs-site.xml.tmpl')
    executeTemplate('/etc/hadoop/conf/mapred-site.xml.tmpl')
    
    #
    # Reset dfs on reboot, this should probably be fixed in future
    run('rm -rf /tmp/hadoop-root /mnt/hadoop', ignoreError=True)
    dirExists('/mnt/hadoop')
    dirOwner('/mnt/hadoop', 'www-data', 'www-data', ignoreError=True)
    run('hadoop namenode -format', ignoreError=True)
    run('chmod -R 777 /mnt/hadoop')

    run('/etc/init.d/hadoop-0.20-namenode start')
    run('/etc/init.d/hadoop-0.20-datanode start')
    run('/etc/init.d/hadoop-0.20-jobtracker start')
    run('/etc/init.d/hadoop-0.20-tasktracker start')
elif sys.argv[1] == 'stop':
    run('/etc/init.d/hadoop-0.20-datanode stop')
    run('/etc/init.d/hadoop-0.20-tasktracker stop')
    run('/etc/init.d/hadoop-0.20-jobtracker stop')
    run('/etc/init.d/hadoop-0.20-namenode stop')
elif sys.argv[1] == 'restart':
    run('/etc/init.d/hadoop-0.20-datanode stop')
    run('/etc/init.d/hadoop-0.20-tasktracker stop')
    run('/etc/init.d/hadoop-0.20-jobtracker stop')
    run('/etc/init.d/hadoop-0.20-namenode stop')
    
    run('/etc/init.d/hadoop-0.20-namenode start')
    run('/etc/init.d/hadoop-0.20-datanode start')
    run('/etc/init.d/hadoop-0.20-jobtracker start')
    run('/etc/init.d/hadoop-0.20-tasktracker start')
else:
    raise Exception('Unknown argument: ' + sys.argv[1])
