#!/bin/bash 

do_start() {
##
#To support ad-hoc virtual clusters, 
#set up mock hostname if we don't have one, using the clovr-IPADDR naming convention
#This is required so that SGE can run locally without problems
    nodns=0
    myhostname=`hostname -f`
    if [ $? != "0" ]
    then
	nodns = 1
    else
	ping -c 1 myhostname
	if [ $? != 0 ]
	    nodns = 1
	fi
    fi
    if [ $nodns = "1" ]
    then
	ipaddr=`/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print ""$2"" }'`
	ipalias=`echo $ipaddr | sed -e 's/\./-/g'`;
	hostname clovr-$ipalias
	cp /etc/hosts.orig /etc/hosts
	echo "$ipaddr clovr-$ipalias clovr-$ipalias" >> /etc/hosts
	if [ -d "/opt/vappio-scripts" ]
	then
	    vappio_scripts=/opt/vappio-scripts
	    . $vappio_scripts/vappio_config.sh
	    touch $vappio_runtime/no_dns
	fi
    fi
}

do_stop() {
    cp /etc/hosts.orig /etc/hosts
}

case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart)
	do_stop
	do_start
	;;
    *)
	echo $"Usage: $0 {start|stop}"
	exit 1
esac

exit $?
