#!/bin/bash 

# Import vappio config
source /root/clovrEnv.sh
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh

#cfg apt sources.list (seperate for ec2 and local)
#localmachineconf (vmware,vbox,xen only)
#mongo (master only)
#ganglia (separate master, exec start scripts)
#hadoop (seperate master, exec start scripts)
#stow (same)
#opt/packages (same)
#localuserdata (vmware,vbox,xen only)

##
# If /tmp/machine.conf already exists then we do not need to make it
# if we are running under VMWare or a local Xen then it will need to
# be created at bootup (Ec2/nimbus should create it during startup process)
export HOME=/root
if [ ! -e /tmp/machine.conf ]
then
    createLocalMachineConf.py --conf=$VAPPIO_HOME/vappio-conf/clovr.conf -o /tmp/machine.conf > /tmp/startUpNode.log 2>&1
    bootStrapKeys.py
fi

##
# Start up all services on the node
startUpNode.py >> /tmp/startUpNode.log 2>&1

vmStatus.py -1 > /tmp/vmStatus.log




