#!/bin/bash 

# Import vappio config
source /root/clovrEnv.sh
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh

#cfg apt sources.list (seperate for ec2 and local)
#localmachineconf (vmware,vbox,xen only)
#mongo (master only)
#ganglia (separate master, exec start scripts)
#hadoop (seperate master, exec start scripts)
#stow (same)
#opt/packages (same)
#localuserdata (vmware,vbox,xen only)

#(1) User scripts
#TODO,split user data file into $user_data_scripts
#See /usr/lib/python2.6/dist-packages/cloudinit/UserDataHandler.py
if [ -d "$user_data_scripts" ]
then
    echo "Running user-scripts in $user_data_scripts"
    run-parts -v "$user_data_scripts"
fi

#(2) Machine conf and bootstrap keys
##
# If /tmp/machine.conf already exists then we do not need to make it
# if we are running under VMWare or a local Xen then it will need to
# be created at bootup (Ec2/nimbus should create it during startup process)
export HOME=/root
createLocalMachineConf.py --conf=/mnt/vappio-conf/clovr.conf -o /tmp/machine.conf > /tmp/startUpNode.log 2>&1
bootStrapKeys.py

#(3) Startup services
##
# Start up all services on the node
startUpNode.py >> /tmp/startUpNode.log 2>&1

vmStatus.py -1 > /tmp/vmStatus.log

