#!/usr/bin/env python
import sys

# Just pull everything from policy
from igs.config_manage.policy import *

def startup():
    dirExists('${dirs.upload_dir}')
    dirExists('${dirs.tag_dir}')
    dirOwner('${dirs.upload_dir}', 'www-data')
    dirOwner('${dirs.tag_dir}', 'www-data')

def shutdown():
    pass


if len(sys.argv) < 2:
    raise Exception('Must provide start|stop|restart')

if sys.argv[1] == 'start':
    startup()
elif sys.argv[1] == 'stop':
    shutdown()
elif sys.argv[1] == 'restart':
    shutdown()
    startup()
else:
    raise Exception('Unknown argument: ' + sys.argv[1])

    
