#!/bin/bash

USAGE="vp-join-cluster master_ip"

##Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh
##

while getopts "h" options; do
  case $options in
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

if [ "$1" = "" ]
then
    echo -e "$USAGE"
    exit 1;
else
    ping $1 -c 1 
    if [ $? != 0 ]
    then
	echo -e "Can't ping master node $1"
	exit 1;
    fi
fi

isreachable=`printf "kv\nhostname=$remotehost\n" | /opt/vappio-metrics/host-is-reachable | grep "reachable=yes"`
if [ "$isreachable" = "" ]
then
    echo -e "Can't connect to master node $1. Ensure that you have a copy of the master node key in /mnt/keys/devel1.pem"
    exit 1;
fi
bootStrapKeys.py
$vappio_scripts/vp-stop-node
echo "$1" > $vappio_userdata/master_node
$vappio_scripts/vp-start-node exec

