#!/bin/bash

USAGE="vp-join-cluster master_ip\n
You must save the master node SSH key in /mnt/keys/devel1.pem before you are able to join a cluster\n"

##Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh
##

while getopts "h" options; do
  case $options in
      h ) echo -e $USAGE
	  exit 1;;
      \? ) echo -e $USAGE
          exit 1;;
  esac
done

if [ "$1" = "" ]
then
    echo -e "$USAGE"
    exit 1;
else
    ping $1 -c 1 
    if [ $? != 0 ]
    then
	echo -e "Can't ping master node $1"
	exit 1;
    fi
fi

isreachable=`printf "kv\nhostname=$1\n" | /opt/vappio-metrics/host-is-reachable | grep "reachable=yes"`
if [ "$isreachable" = "" ]
then
    echo -e "Can't connect to master node $1"
    echo -e "Ensure that you have obtained copy of the master node public key and save as /mnt/keys/devel1.pem.pub"
    exit 1;
fi
bootStrapKeys.py
$vappio_scripts/vp-stop-node
echo "$1" > $vappio_userdata/master_node
$vappio_scripts/vp-start-node exec

