#!/bin/bash

#USAGE: vp-start-node types

##Import vappio config
vappio_scripts=/opt/vappio-scripts
source $vappio_scripts/vappio_config.sh
##

vlog "###"
vlog "### $0 (`whoami`)"
vlog "###"

if [ "$1" = "" ]
then
    echo "vp-start-node type1 [type2 ... typen]"
    exit 1
fi

nodetype=$1

#Node type startup scripts
for n in $@
do
    if [ -d "/etc/vappio/$n" ]
    then
	echo "INIT NODETYPE $n" 
	run-parts -v --regex '^S.*' --arg start /etc/vappio/$n/ 
    else
	echo "Skipping node type with no configuration: $nodetype"
    fi
done

echo "$nodetype" > $vappio_runtime/node_type




