#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update
$VAPPIO_HOME/vappio-install/vp-bootstrap-install

bash -e $VAPPIO_RECIPES/setup.sh
bash -e $VAPPIO_RECIPES/sysconfigs.sh
bash -e $VAPPIO_RECIPES/hpnssh.sh
bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/vappiopkg.sh
bash -e $VAPPIO_RECIPES/vappiocustoms.sh
bash -e $VAPPIO_RECIPES/vappio-metrics.sh
bash -e $VAPPIO_RECIPES/ganglia.sh
bash -e $VAPPIO_RECIPES/sge.sh
bash -e $VAPPIO_RECIPES/hadoop.sh

#catch all for cpanmod
bash -e $VAPPIO_RECIPES/cpanmods.sh
bash -e $VAPPIO_RECIPES/vappiosite.sh
bash -e $VAPPIO_RECIPES/clovrsetup.sh
#catch all for apt pkgs
bash -e $VAPPIO_RECIPES/generalpkgs.sh
bash -e $VAPPIO_RECIPES/rpkg.sh
bash -e $VAPPIO_RECIPES/workflow.sh
bash -e $VAPPIO_RECIPES/ergatis.sh

bash -e $VAPPIO_RECIPES/igsaengine.sh

#was bash -e $VAPPIO_RECIPES/bioifxtools.sh
bash -e $VAPPIO_RECIPES/biolinux.sh
bash -e $VAPPIO_RECIPES/ubuntuifxpkgs.sh
bash -e $VAPPIO_RECIPES/qiime.sh
bash -e $VAPPIO_RECIPES/amos.sh

#was bash -e $VAPPIO_RECIPES/clovrmain.sh
bash -e $VAPPIO_RECIPES/clovroptpackages.sh
bash -e $VAPPIO_RECIPES/clovrstow.sh
bash -e $VAPPIO_RECIPES/clovrpipelines.sh

bash -e $VAPPIO_RECIPES/clovrdashboard.sh

bash -e $VAPPIO_RECIPES/apache.sh

bash -e $VAPPIO_RECIPES/hudson.sh
