#!/bin/bash

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/hudson.sh
#Need grub legacy, it just works with xen
#tried grub2 but it is a mess
apt-get -y install qemu-kvm grub

#Retrieve grub and boot sector 
wget -c /mnt http://cb2.igs.umaryland.edu/grub-boot.tgz

#chroot
#update-initramfs
#create grub.cfg
#update-grub 
#grub-install
