#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update
$VAPPIO_HOME/vappio-install/vp-bootstrap-install

bash -e $VAPPIO_RECIPES/setup.sh
bash -e $VAPPIO_RECIPES/sysconfigs.sh
bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/vappiopkg.sh
bash -e $VAPPIO_RECIPES/hudson.sh
sudo bash -e $VAPPIO_RECIPES/buildutils.sh

#Additional hudson configuration for the build box only
#Set executors to 2
#<numExecutors>2</numExecutors>
#Set default view to platform conversion
#<primaryView>CloVR tests</primaryView>
svn export --force https://clovr.svn.sourceforge.net/svnroot/clovr/trunk/hudson/hudson-config/config.xml.clovr-build /var/lib/hudson/config.xml
