#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update
$VAPPIO_HOME/vappio-install/vp-bootstrap-install

bash -e $VAPPIO_RECIPES/setup.sh
bash -e $VAPPIO_RECIPES/sysconfigs.sh
bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/vappiopkg.sh
bash -e $VAPPIO_RECIPES/hudson.sh
sudo bash -e $VAPPIO_RECIPES/buildutils.sh

#Additional hudson configuration for the build box only
#Set executors to 2
#<numExecutors>2</numExecutors>
#Set default view to platform conversion
#<primaryView>CloVR tests</primaryView>
svn export --force https://clovr.svn.sourceforge.net/svnroot/clovr/trunk/hudson/hudson-config/config.xml.clovr-build /var/lib/hudson/config.xml
echo "Enabling updates and hudson start at boot"
mkdir -p /mnt/user-scripts
echo '#!/bin/bash' > /mnt/user-scripts/01-updaterecipes
echo '/opt/vappio-install/vp-bootstrap-install' >> /mnt/user-scripts/01-updaterecipes
echo '#!/bin/bash' > /mnt/user-scripts/02-starthudson
echo '/etc/init.d/hudson start' >> /mnt/user-scripts/02-starthudson
echo '#!/bin/bash' > /mnt/user-scripts/03-startaptcacher
echo '/etc/init.d/apt-cacher restart' >> /mnt/user-scripts/03-startaptcacher

