#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update
$VAPPIO_HOME/vappio-install/vp-bootstrap-install

bash -e $VAPPIO_RECIPES/setup.sh
bash -e $VAPPIO_RECIPES/sysconfigs.sh
bash -e $VAPPIO_RECIPES/hpnssh.sh
bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/vappiopkg.sh
bash -e $VAPPIO_RECIPES/vappiocustoms.sh
bash -e $VAPPIO_RECIPES/ganglia.sh
bash -e $VAPPIO_RECIPES/sge.sh
bash -e $VAPPIO_RECIPES/hadoop.sh
#bash -e $VAPPIO_RECIPES/gridftp.sh
