#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update
$VAPPIO_HOME/vappio-install/vp-bootstrap-install

#Setup virgin image
bash -e $VAPPIO_RECIPES/setup.sh
#Basic system config
bash -e $VAPPIO_RECIPES/sysconfigs.sh
bash -e $VAPPIO_RECIPES/disablesplash.sh
#Requires clovrsplash.sh is passed to vp-bundle-release


#bash -e $VAPPIO_RECIPES/useradd.sh

#High performance SSH
bash -e $VAPPIO_RECIPES/hpnssh.sh
bash -e $VAPPIO_RECIPES/allowrootssh.sh

#Vappio appliance utils
bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/vappiopkg.sh
bash -e $VAPPIO_RECIPES/sethostname.sh
bash -e $VAPPIO_RECIPES/autologin.sh
bash -e $VAPPIO_RECIPES/dhcp.sh


bash -e $VAPPIO_RECIPES/vappiocustoms.sh
bash -e $VAPPIO_RECIPES/vappio-tasklets.sh

#Hudson, install this early because it fails a lot due to network
#issues
bash -e $VAPPIO_RECIPES/hudson.sh

#Grid utils
bash -e $VAPPIO_RECIPES/ganglia.sh
bash -e $VAPPIO_RECIPES/sge.sh
bash -e $VAPPIO_RECIPES/hadoop.sh

#catch all for cpanmod
bash -e $VAPPIO_RECIPES/cpanmods.sh
bash -e $VAPPIO_RECIPES/vappiosite.sh

bash -e $VAPPIO_RECIPES/clovrsetup.sh

#catch all for apt pkgs
bash -e $VAPPIO_RECIPES/generalpkgs.sh

#R
bash -e $VAPPIO_RECIPES/rpkg.sh

#Workflow and Ergatis
bash -e $VAPPIO_RECIPES/workflow.sh
bash -e $VAPPIO_RECIPES/ergatis.sh

#Deps for aengine
bash -e $VAPPIO_RECIPES/igsaengine.sh

#Biolinux and other bioifx packages
bash -e $VAPPIO_RECIPES/biolinux.sh
bash -e $VAPPIO_RECIPES/ubuntuifxpkgs.sh

#Qiime
bash -e $VAPPIO_RECIPES/qiime.sh

#AMOS
bash -e $VAPPIO_RECIPES/amos.sh

#Non-standard packages
bash -e $VAPPIO_RECIPES/clovroptpackages.sh
bash -e $VAPPIO_RECIPES/clovrstow.sh

#CloVR pipelines
bash -e $VAPPIO_RECIPES/clovrpipelines.sh

#CloVR GUI
bash -e $VAPPIO_RECIPES/clovrdashboard.sh

#Apache config
bash -e $VAPPIO_RECIPES/apache.sh

# Adds an older version of ec2 tools and tools needed for nimbus
#remove -e due to transient failures at nimbusproject.org
bash $VAPPIO_RECIPES/nimbus.sh

# Adds symbolic link from /opt/opt-packages/bioinf-v1r4b1//MUSCLE//muscle
# to /usr/local/bin/muscle
bash -e $VAPPIO_RECIPES/clovrcomparative.sh

# Pypi and any python modules
bash $VAPPIO_RECIPES/pypi.sh

#Gbrowse2
#Skip errors for now
bash $VAPPIO_RECIPES/gbrowse2.sh

#ExtJS
bash $VAPPIO_RECIPES/extjs.sh

#BWA
bash $VAPPIO_RECIPES/bwa.sh

# clovr microbe
bash $VAPPIO_RECIPES/circleator.sh
bash $VAPPIO_RECIPES/batik.sh

#TODO
#updating clovr SVN filesystem packages/packages.list cpan.packages
#making svn tags

echo -n "" > /etc/hostname
