#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update

bash -e $VAPPIO_RECIPES/cpanmods.sh
bash -e $VAPPIO_RECIPES/vappiosite.sh
bash -e $VAPPIO_RECIPES/clovrsetup.sh
bash -e $VAPPIO_RECIPES/generalpkgs.sh
bash -e $VAPPIO_RECIPES/workflow.sh

bash -e $VAPPIO_RECIPES/ergatis.sh
bash -e $VAPPIO_RECIPES/igsaengine.sh
bash -e $VAPPIO_RECIPES/bioifxtools.sh
bash -e $VAPPIO_RECIPES/clovrmain.sh

bash -e $VAPPIO_RECIPES/clovrdashboard.sh

bash -e $VAPPIO_RECIPES/apache.sh