#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update

bash -e $VAPPIO_RECIPES/setup.sh
bash -e $VAPPIO_RECIPES/sysconfigs.sh
bash -e $VAPPIO_RECIPES/vappioutil.sh
bash -e $VAPPIO_RECIPES/vappiopkg.sh
bash -e $VAPPIO_RECIPES/buildutils.sh
bash -e $VAPPIO_RECIPES/hudson.sh

