#!/bin/bash

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

$VAPPIO_RECIPES/vappioutil.sh
$VAPPIO_RECIPES/hudson.sh
apt-get -y install qemu-kvm
#Retrieve grub and boot sector 

wget grub-boot.tgz


#chroot
#update-initramfs
#create grub.cfg
#update-grub 
#grub-install
