#!/bin/bash

$VAPPIO_HOME=/opt
$VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

$VAPPIO_RECIPES/setup.sh
$VAPPIO_RECIPES/sysconfigs.sh
$VAPPIO_RECIPES/hpnssh.sh
$VAPPIO_RECIPES/vappiocustoms.sh
$VAPPIO_RECIPES/vappiopkg.sh

