#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt/
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update

bash -e $VAPPIO_RECIPES/setup.sh
bash -e $VAPPIO_RECIPES/sysconfigs.sh

#To enable ssh login on skeleton image
#Use passwordless login via console 
#Edit /etc/ssh/sshd_config
#ChallengeResponseAuthentication yes
#PasswordAuthentication yes
#/etc/init.d/ssh restart