#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

VAPPIO_HOME=/opt
VAPPIO_RECIPES=$VAPPIO_HOME/vappio-install/recipes

apt-get -y update
$VAPPIO_HOME/vappio-install/vp-bootstrap-install

#Setup virgin image
bash -e $VAPPIO_RECIPES/setup.sh
#Basic system config
bash -e $VAPPIO_RECIPES/sysconfigs.sh
#We can't completely remove the above two recipes so
#temporarily need to remove some things added by other recipes
#TODO, break apart recipes to avoid this in the future
rm -f /etc/profile.d/vp-screenlogin
rm -rf /opt/vappio-py /etc/vappio-checkout
#TODO set custom /etc/environment 

# Installing software requirements
# Avoiding upgrade because it failes in grub
# apt-get --force-yes -y upgrade
apt-get --force-yes -y install ubuntu-desktop openjdk-6-jdk libxml2 libxslt1.1
apt-get --force-yes -y install libxslt1-dev ant subversion build-essential 
apt-get --force-yes -y install zlib1g-dev libpng12-dev libfreetype6-dev mpich2
apt-get --force-yes -y install libreadline-dev libgsl0-dev gfortran
# nfs-common libqt3-mt-headers 
apt-get --force-yes -y install nfs-kernel-server libqt4-dev 
apt-get --force-yes -y install subversion r-base libqt3-mt-dev libqt3-headers
# Accepting java license
echo sun-java6-plugin shared/accepted-sun-dlj-v1-1 select true | /usr/bin/debconf-set-selections
apt-get --force-yes -y install sun-java6-plugin

# Creating qiime user & setting up environment
addgroup qiime
useradd -g qiime -m qiime -s /bin/bash
#echo "qiime" | passwd --stdin qiime
touch /home/qiime/.bashrc
chown qiime:qiime /home/qiime/.bashrc

echo "qiime ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

chmod 777 /tmp
userdel -r ubuntu

mkdir /media/

# Installing qiime-deploy
mkdir /software/
chown qiime:qiime /software/
mkdir /software/qiime-deploy/
svn co svn://svn.microbio.me/QiimeUtils/qiime_installer/vb-upgrade/qiime-deploy /software/qiime-deploy
find /software -type f -exec chmod 666 {} \;
find /software -type d -exec chmod 777 {} \;
find /software -exec chown qiime:qiime {} \;
pushd /software/qiime-deploy/
python /software/qiime-deploy/qiime-deploy.py -r -p /software/ --userhome /home/qiime/
popd
find /software -exec chown qiime:qiime {} \;	

# Stop some services that are started during installations
killall cupsd

# Forcing some settings
rm -f /etc/apt/apt.conf.d/01proxy
apt-get --force-yes -y autoremove
apt-get --force-yes -y clean

### 
### Adding extra configurations for the virtual machine
###

# Setting up extra folders
sudo -u qiime mkdir /home/qiime/Desktop
sudo -u qiime mkdir /home/qiime/Desktop/Before_you_start/
sudo -u qiime mkdir /home/qiime/Desktop/Shared_Folder

# ==> Adding link to the Before_you_start files
ln -s /software/qiime-1.2.0-release/doc/vb_files/Before_you_start/0.QIIME_version.txt /home/qiime/Desktop/Before_you_start/0.QIIME_version.txt
ln -s /software/qiime-1.2.0-release/doc/vb_files/Before_you_start/1.Welcome.txt /home/qiime/Desktop/Before_you_start/1.Welcome.txt
ln -s /software/qiime-1.2.0-release/doc/vb_files/Before_you_start/2.Fixing_Internet_access_in_the_virtual_box.txt /home/qiime/Desktop/Before_you_start/2.Fixing_Internet_access_in_the_virtual_box.txt
ln -s /software/qiime-1.2.0-release/doc/vb_files/Before_you_start/3.Getting_started_with_QIIME.txt /home/qiime/Desktop/Before_you_start/3.Getting_started_with_QIIME.txt
ln -s /software/qiime-1.2.0-release/doc/vb_files/Before_you_start/4.Transferring_files_to_your_virtual_box.txt /home/qiime/Desktop/Before_you_start/4.Transferring_files_to_your_virtual_box.txt

# ==> 3. Disable disk check after 20 reboots
# ... done by CLoVR

# ==> Remove autoupdate
# ... done by CLoVR

# ==> Rename hostname
echo "qiimevm" > /etc/hostname
hostname -b -F /etc/hostname

# ==> Adding Shared Folder
echo "mount.vboxsf -w -o uid=1001 Shared_Folder /home/qiime/Desktop/Shared_Folder" >> /etc/rc.local

# ==> Make sym link to documentation.html
ln -s /software/qiime-1.2.0-release/doc/_build/html/index.html /home/qiime/Desktop/Before_you_start/documentation.html

# ==> Make sym link to /software/
ln -s /software/ /home/qiime/Desktop/software

# ==> Remove all sounds
# ==> Make sym link to terminal in the top menu
# ==> Changing background 
cd /home/qiime/
svn export svn://svn.microbio.me/QiimeUtils/qiime_installer/clovr/xinitrc .xinitrc
chown qiime:qiime /home/qiime/.xinitrc
mkdir /usr/local/qiime_home/
cd /usr/local/qiime_home/
svn export svn://svn.microbio.me/QiimeUtils/qiime_installer/clovr/gconf.tgz
tar zxvf gconf.tgz 
rm gconf.tgz
chown -R qiime:qiime /usr/local/qiime_home/

# ==> Allowing turning off, rebooting and autologin
chmod +s /sbin/reboot
chmod +s /sbin/shutdown
chmod +s /sbin/initctl

# ==> Allow user to write on qiime_tutorial but not remove the files

# ==> Testing
#_full_ pycogent test suite on the installed library, including setting the environment TEST_DB=1